### ISSUE TITLE
WasmQueryErrorPrevent Error

### ISSUE THREAD

**Issue by losek1** [KrzysztofZawisla/WasmQuery#3]
While "WasmQueryErrorPrevent" is set to true, function $("input").css("font-size", ["5px", "10px", "15px", "20px"]) returned (4) ["5px", "10px", "15px", "20px"]

**Comment by KrzysztofZawisla** [comment]
I've already fix this issue in this update https://github.com/KrzysztofZawisla/WasmQuery/commit/c58e4341c9f669c57ac032041e9d7d08081a5279
Thanks for help.
